#!/usr/bin/env python3
"""Read the `homepage` field of every repository listed in data/projects.js
and write the results to data/live.js.

The curated file (data/projects.js) is never touched: live URLs live in their
own generated file, so a hand edit and a sync can never collide.
"""
import json, os, re, sys, urllib.request, urllib.error

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "projects.js")
OUT = os.path.join(ROOT, "data", "live.js")
API = "https://api.github.com/repos/{}/{}"

def entries():
    """Pull (id, owner, repo) out of the curated project list."""
    text = open(SRC, encoding="utf-8").read()
    for m in re.finditer(r'id:\s*"([^"]+)"[^}]*?repo:\s*"https://github\.com/([^/"]+)/([^/"]+)"', text):
        yield m.group(1), m.group(2), m.group(3)

def homepage(owner, repo, token):
    req = urllib.request.Request(API.format(owner, repo),
                                 headers={"Accept": "application/vnd.github+json",
                                          "User-Agent": "daniel-rck-site-sync"})
    if token:
        req.add_header("Authorization", "Bearer " + token)
    try:
        with urllib.request.urlopen(req, timeout=25) as r:
            data = json.load(r)
    except urllib.error.HTTPError as e:
        print("  ! {}/{}: HTTP {}".format(owner, repo, e.code), file=sys.stderr)
        return None
    except Exception as e:
        print("  ! {}/{}: {}".format(owner, repo, e), file=sys.stderr)
        return None
    url = (data.get("homepage") or "").strip()
    if not url:
        return None
    if not url.startswith(("http://", "https://")):
        url = "https://" + url
    # A homepage pointing back at GitHub (a wiki, the repo itself, a release
    # page) is documentation, not a live app — the site already links the repo.
    if re.match(r"https?://(www\.)?github\.com/", url):
        return None
    return url

def main():
    token = os.environ.get("GITHUB_TOKEN", "")
    live, missing = {}, []
    for pid, owner, repo in entries():
        url = homepage(owner, repo, token)
        if url:
            live[pid] = url
            print("  + {:<24} {}".format(pid, url))
        else:
            missing.append(pid)
    if missing:
        print("  - no homepage set: " + ", ".join(missing))

    body = json.dumps(live, indent=2, ensure_ascii=False, sort_keys=True)
    open(OUT, "w", encoding="utf-8").write(
        "/* Generated by scripts/sync-live-urls.py — do not edit by hand.\n"
        "   Source of truth is each repository's About > Website field on GitHub. */\n"
        "window.LIVE = " + body + ";\n")
    print("\n{} live URL(s) written to data/live.js".format(len(live)))

if __name__ == "__main__":
    main()
